FROM --platform=linux/amd64 ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

ENV DEBIAN_FRONTEND=noninteractive

# Enable multi-arch support
RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y \
    libasound2-dev:arm64 \
    clang \
    libclang-dev
